### ISSUE TITLE
ajax-handler.php 404

### ISSUE THREAD

**Issue by Terminal-Access** [RensTillmann/super-forms#10]
Hey, guys love this plugin, thanks for all your hard work!

As of your recent update v4.6.5 sadly I am unable to edit or create any forms, I get the following error in the console.

**Brave Browser:**
`POST https://static.brutal.co.uk/plugins/super-forms/includes/ajax-handler.php 404`

**Firefox Browser:**
```
Source map error: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
Resource URL: https://static.brutal.co.uk/plugins/super-forms/assets/css/frontend/elements.css?ver=4.6.5
Source Map URL: elements.css.map
```

I have noticed that it's only due to the new ajax-handler implementation that's now causing the error if I, for instance, revert back to a previous version it's working fine.

My Current Setup:
Wordpress V5.2
SuperForms V4.6.5
PHP v7.2

thanks guys.

**Comment by RensTillmann** [comment]
Hi, thanks for the information, however this is not happening on our end so it might be server related or form related, please contact support through codecanyon and provide license and a login to your wp-admin + FTP.

**Comment by RensTillmann** [comment]
Just an update on this, I completely reverted back to the default WP ajax handler, because it was causing to many problems in the end, even though the custom handler was handling request faster, it wasn't worth it.
