### ISSUE TITLE
Accept E-mails with + in username portion

### ISSUE THREAD

**Issue by jbeales** [RensTillmann/super-forms#14]
When a form field has a "Special Validation" set to "Email address" it says that an E-mail address with a + in the username portion, (for example: `john+test@example.com`) is invalid and won't submit the form. This is a valid E-mail address.

Could the form validation be updated to accept E-mail addresses with + in the username portion?

**Comment by RensTillmann** [comment]
Hi, I just pushed a commit that allows the use of a "+" symbol in the username portion. It will be included in the next release. Thanks.
