### ISSUE TITLE
Issue with re-direct

### ISSUE THREAD

**Issue by Lilly-sander** [RensTillmann/super-forms#15]
- When I try to Disable the Thank you message, (I click Save) and I refresh page, it doesnt respect that I want to disable the "Thank You message"

- When I enable the Redirect Page to the Bottom (directly added from the form builder), its doesn´t save the contact entry and it doesnt send the mail to the admin.

**Comment by RensTillmann** [comment]
Hi, 1) make sure to change the settings on form level 2) make sure to set a redirect on the form settings, and not on a custom button, because it would just act as a "link".

**Comment by RensTillmann** [comment]
Sorry if you misunderstood, but when I mean on Form Level, I mean here:

http://i.imgur.com/yVTNwfl.png
