### ISSUE TITLE
SuperForm - CSS Slider property causing issues

### ISSUE THREAD

**Issue by jrameriz** [RensTillmann/super-forms#21]
I have a website that's using superforms and the css is causing an issue on my home page. the CSS property slider is causing my image to adopt your css property. 
see example: https://apps.raypak.com/

**Comment by RensTillmann** [comment]
Hi, thanks for reporting this, we will make sure that this library has a "super" prefix in the stylesheet and in the class selector in HTML so it no longer conflicts with other elements on your site.

**Comment by jrameriz** [comment]
Thank you! that should fix it!

**Comment by RensTillmann** [comment]
Hi, the last release contains a fix for this. Version will be released soon.
