### ISSUE TITLE
SUPER.init_skype is not a function

### ISSUE THREAD

**Issue by seiwonlee** [RensTillmann/super-forms#24]
Hi there,

I am using v. 4.9.2 and getting this error:

common.js?ver=4.9.200:4781 Uncaught TypeError: SUPER.init_skype is not a function
    at Object.SUPER.init_super_form_frontend (common.js?ver=4.9.200:4781)
    at HTMLDocument.<anonymous> (common.js?ver=4.9.200:18)
    at i (jquery.js?ver=1.12.4-wp:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4-wp:2)
    at Function.ready (jquery.js?ver=1.12.4-wp:2)

<img width="317" alt="error2" src="https://user-images.githubusercontent.com/1533123/79055188-08176900-7c19-11ea-8f6a-08f4ab69e382.png">
<img width="469" alt="error1" src="https://user-images.githubusercontent.com/1533123/79055189-08176900-7c19-11ea-8a23-298a090fad60.png">

The forms are just showing the "spinner" due to the errors above.

Can you please help?

**Comment by RensTillmann** [comment]
Hi, I don't understand, because since v4.7.63 that function was removed and it no longer exists inside the common.js file. Perhaps you need to empty cache? Otherwise download the latest version from Envato agin.

**Comment by seiwonlee** [comment]
Just for reference, it happened that CDN was caching that javascript file. I'm not sure why but now our site is serving up the latest. Thanks.
