### ISSUE TITLE
Question and suggestion

### ISSUE THREAD

**Issue by codeorlov** [RensTillmann/super-forms#26]
**1.** Hello, please tell me, I have a form that consists of 3 steps, on the third page I would like to display the result of what the user entered or pressed, but the {loop_label {loop_value} tags do not work. How can i do this?
[Form URL](https://pasteleriaviolet.com/pedido-tarta-red-velvet/)
**2.** My clients really want to be able to send the form not by mail but directly to modern messengers, whatsapp, facebook, telegram etc, now the whole small electronic business is built on this. Is there such an opportunity now? Are you planning to add this?

**Comment by RensTillmann** [comment]
1. you can use foreach loops in HTML element: https://renstillmann.github.io/super-forms/#/email-foreach-loops

2. you might be able to do this with the Zapier Add-on.

**Comment by codeorlov** [comment]
1. Thank you.
2. Unfortunately, zapier does not support telegram, nor viber, nor whatsap, only facebook, unfortunately this solution does not fit.

**Comment by RensTillmann** [comment]
Zapier does support whatsapp, telegram and viber:

https://zapier.com/apps/viber/integrations
https://zapier.com/apps/whatsapp-messenger
https://zapier.com/apps/telegram/integrations

**Comment by codeorlov** [comment]
@RensTillmann 
this is just a description of the messengers, click at the top of Integration and you will see that
Hi "WhatsApp Messenger Customers
WhatsApp Messenger has not yet built an integration on Zapier. "

**Comment by RensTillmann** [comment]
Ok, I see, it says "upcoming" on the left. I guess you will have to wait for it. I have no plans integrating any of these things. You will have to hire a developer for this.

**Comment by codeorlov** [comment]
@RensTillmann 
yes, waiting for more than a year :) then I suggested that you create a new plug-in that would bring your product to a completely different level, since no one has it. I hope you think about it, it will help sales a lot :)

**Comment by RensTillmann** [comment]
I see, I will note it down for now as feature improvement. However it won't be anytime soon.
