### ISSUE TITLE
The problem with adding html label radiobutton

### ISSUE THREAD

**Issue by joylord** [RensTillmann/super-forms#27]
hi
I have a problem adding html radiobutton label.
фаеук updating the field my quotes are removed and backslash is added and the code is as follows
`<span style=\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"color: #339966;\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\">TEXT</span>`
After each update, a backslash is added.

**Comment by RensTillmann** [comment]
This should be fixed in v4.9.450, please let me know.
