### ISSUE TITLE
Problem with foreign language requests

### ISSUE THREAD

**Issue by vvndnk** [RensTillmann/super-forms#30]
Hey, hope you can help me with my problem.

Recently we have had problems with some of our forms. Forms that come from customers who use our website in another language are incorrectly displayed to us. (our website is only available in German, customers translate the page manually)

Here is an example of how the request is received by us:

Conditions: 44.00 <font style = "vertical-align: inherit;"> <font style = "vertical-align: inherit;"> € for 4 weeks (28 days) </font> </font>
Date: undefined, NaN undefined, NaN

Usually the price and the date are shown here.

We would be very grateful if you could help us with that. If you need more information, let me know.

Best regards

Vivien

**Comment by RensTillmann** [comment]
Hi, not sure if you also contact support and if this issue was already solved, if not please could you provide the form export here, then I will take a look into this issue and see if there is a workaround.
