### ISSUE TITLE
Hook filter to add/remove/alter data before saving it to database (contact entry)

### ISSUE THREAD

**Issue by Zeldri** [RensTillmann/super-forms#33]
Hi,
Is there a hook filter that can be use to edit data from a form submission before being save as contact entry/database ?
That's because I would like to add data that don't need to be display to the form, I know there is a way to autopopulate from $_GET or $_POST from other forms but because I'm using a rewrite rule, the $_GET parameters are not being catch by superform or PHP but only with query_vars

**Comment by RensTillmann** [comment]
Yes, please read here for available hooks and example codes: [https://renstillmann.github.io/super-forms/#/introduction-hooks](https://renstillmann.github.io/super-forms/#/introduction-hooks)
