### ISSUE TITLE
Console css map issue

### ISSUE THREAD

**Issue by jrameriz** [RensTillmann/super-forms#34]
Browser loads DevTools failed to load SourceMap: Could not load content for .../wp-content/plugins/super-forms/assets/css/frontend/elements.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by RensTillmann** [comment]
Hi, that file is excluded from distro, hence you get this warning when you open devtools. This isn't an error and will not break any features. If you need the sourcemap you can find it here: https://github.com/RensTillmann/super-forms/tree/master/src/assets/css/frontend
