### ISSUE TITLE
Tranlate for "Uploading Files" popup when form is sent

### ISSUE THREAD

**Issue by tivendo** [RensTillmann/super-forms#63]
If I have an upload field on the form and the user clicks on the send button, they will see a popup with "Uploading Files" text. Please make this translatable.

**Comment by RensTillmann** [comment]
Hi, but it's already translatable :)

https://github.com/RensTillmann/super-forms/blob/8ada92e0440298b18220c6ff7d84a4ca43d3ee00/src/super-forms.php#L1567
