### ISSUE TITLE
superforms - error adding csv or conditional statements

### ISSUE THREAD

**Issue by jrameriz** [RensTillmann/super-forms#64]
https://youtu.be/syEabxgI5F0

This error goes back to our discussion with conditional statements not allowing  conditional statements to be added. Could be different but acting the same. 
https://github.com/RensTillmann/super-forms/discussions/58

**Comment by RensTillmann** [comment]
Do you mean that when you "Delete" the CSV attachment, that the page scrolls to the top (leaving the editing element in the current view)? Is that what you mean. This is definitely not related to that other issue, but I will see if this can be patched in the upcoming release.

**Comment by jrameriz** [comment]
Thank you for the clarification! That is exactly what I was referring too!

**Comment by RensTillmann** [comment]
[v6.2.0](https://github.com/RensTillmann/super-forms/releases/tag/v6.2.0) contains a fix for this issue, thanks for the report 👍
