### ISSUE TITLE
WooCommerce checkout field filled with form tag, when it should come empty from form

### ISSUE THREAD

**Issue by tivendo** [RensTillmann/super-forms#69]
### Discussed in https://github.com/RensTillmann/super-forms/discussions/68

<div type='discussions-op-text'>

<sup>Originally posted by **tivendo** April 30, 2022</sup>
Hey,

absolute amazing what you have build here, congratulations!

One quick question, how do I get a value from my form at the WooCommerce checkout page? I dont need it as input field or something like that, I just need to check if the value is filled. If it's filled I can unset billing_company. If its not filled, I have to show the field billing_company.

I need to do this, because on my form I have a selection if someone is a private person or a company. If it is a private person, the company input field is hidden. Till here, everything is fine. But after filling the form and going to WooCommerce checkout, the original WooCommerce billing_company field is filled with my tag from the form; in this case "{Billing_Firma}". 

this is not good as the field is also present on the invoice, in the mails etc.

Thanks for your answer and best regards. Keep up the good work!

Luis</div>

**Comment by RensTillmann** [comment]
See discussion: [https://github.com/RensTillmann/super-forms/discussions/68](https://github.com/RensTillmann/super-forms/discussions/68)
