### ISSUE TITLE
Selection list cutting off

### ISSUE THREAD

**Issue by Seifertson** [RensTillmann/super-forms#7]
When I'm using a multi-form setup with a selection list it is getting cut off.

Here is a screenshot: https://i.imgur.com/NoG5iFO.png

Any fix?

**Comment by RensTillmann** [comment]
High, sorry for late reply for some reason I don't get notifications on this repo, i have just enabled notifications. Regarding your issue even though it is dated from Nov 14, a simply fix would be to add a "Spacer" element below the dropdown, just give it a 150px height or something will do :) Regarding this bug, it's kind of a design flaw, which will be solved in the next big release, please also note that this repo is a development repository and not intended for live usage. Only the codecanyon release should be used.
