### ISSUE TITLE
How to create Grouped Dropdown?

### ISSUE THREAD

**Issue by tieroneco** [RensTillmann/super-forms#72]
Hello Guys,

Can anyone please tell us how can we create grouped dropdown like this https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_optgroup?

Thank you

**Comment by tieroneco** [comment]
Please help me out.

**Comment by RensTillmann** [comment]
Hi,

Super Forms does not support this, the alternative method is to create a dropdown "origin_country" with the countries.
Then for each country a dropdown with the brands of the cars. And apply the conditional logic on each of them.
Then when you choose "German cars", you can show the dropdown named "german_brands" and display Mercedese etc.

**Comment by tieroneco** [comment]
> Hi,
> 
> Super Forms does not support this, the alternative method is to create a dropdown "origin_country" with the countries. Then for each country a dropdown with the brands of the cars. And apply the conditional logic on each of them. Then when you choose "German cars", you can show the dropdown named "german_brands" and display Mercedese etc.

Okay, I will do that. Thank you.
